FROM nginx:alpine

# the arguments describing the title
ARG part=2
ARG title="Rocky"
ARG year=1979
ARG description="Rocky struggles in family life after his bout with Apollo Creed, while the embarrassed champ insistently goads him to accept a challenge for a rematch."
ARG imdb="https://www.imdb.com/title/tt0079817"

# metadata labels
LABEL maintainer="Pety <pety.barczi@gmail.com>"
LABEL title="$title"
LABEL year="$year"
LABEL description="$description"
LABEL imdb="$imdb"
LABEL part="$part"

# environment variables
ENV part=$part
ENV title=$title
ENV year=$year
ENV description=$description
ENV imdb=$imdb

RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/nginx.conf
ADD index.html /usr/share/nginx/html/index.html

ADD images/rocky.$part.jpg usr/share/nginx/html/images/rocky.$part.jpg
ADD css/rambo.$part.css usr/share/nginx/html/css/rocky.$part.css

RUN sed -e "s/{{TITLE}}/${title}/g" \
        -e "s/{{YEAR}}/${year}/g" \
        -e "s/{{DESCRIPTION}}/${description}/g" \
        -e "s/{{PART}}/${part}/g" \
        -e "s|{{IMDB}}|${imdb}|g" \
        -i /usr/share/nginx/html/index.html
