name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        ls -la
        #echo "${{ secrets.DOCKERPW }}" | docker login -u petyb --password-stdin
        #docker image build -t petyb/rocky:1 -f Dockerfile.1 .
        #docker push petyb/rocky:1

