name: Rocky app 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Images
      run: |
        echo "${{ secrets.DOCKERHUBPW }}" | docker login -u petyb --password-stdin
        echo "Building Image 1"
        docker image build -t petyb/rocky:1 -f Dockerfile.1 .
        docker push petyb/rocky:1
        echo "Building Image 2"
        docker image build -t petyb/rocky:2 -f Dockerfile.2 .
        docker push petyb/rocky:2
        echo "Building Image 3"
        docker image build -t petyb/rocky:3 -f Dockerfile.3 .
        docker push petyb/rocky:3
